sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
deploy:
  provider: pypi
  skip_existing: true
  user: brndnmtthws
  password:
    secure: UtLhZlSfL8aBwSIZT9fnoWhF7McNidc3OELP+MexjDJ3i7cJaiNByDFCPyeUOf9QIwDT2HBidiMz+zvvhWw0azjZ8RB8DaZRy8FPwhkiEnR23FieLb0mRDFxXuGkQ/zjnVbTx6lB5Dx1ssnOF5lqwwVnMGJ4nJB3S8Nnd1Is38o0lGyH1MgWKAFwYpibvQXwLoOGvTkJ8x1n2Bb4ZKxQa3m5MParNq12T1lPoHKJXGPMYhrDRHFan4d9ho0w+0hMuww6R5P1LQezAp3kHlXn2gaaALp/wHNWXxgXiOJ9sk+9N2z1ZDm6kBuIg5dh07hyXPAxUXGbsVcKKkj5/GHFFHJaMg7ZBdLXThQ+b5NXNIMnTPyWHli6683ZPzCItXZ0fOqLA3rWQwGmIx0tdExM0ncbyKiAz0H5ktPp+UlxLBWhCD4yGLFhu5h1GdaaUGL2RdBOBX4nZ3SRYL27SZ3TKmyEdiUc66EzoTo7abjGqgYjyJ9gDfE/9IwMv8nTIMsEJXPGwkaymVuI1NrFXxOSv/0i4qAq0bKZurb2EPOJPgA82nQ9nZRt0Eoe5ovL6wHkcxu9J9JCCuKkPJthTOcdEA9tLHB2f1HqLbDu2045ikcaIiWeEPWCGoNKJUJHBba0sBMY18y3K+z+v02Xyt4eb16kIsDUJyEgkT3H3Q1VxGE=
  on:
    tags: true
install:
  - pip install .
script:
  - gitlab-gce-autoscaler --help
cache: pip
